In [1]:
%magic

In [2]:
%lsmagic


Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3

#keyboard shortcut

shift-enter: execute the current cell
up arrow: upper one cell
down arrow: down one cell

a: insert cell above
b: insert cell below
h: get a list of keyboard shortcuts
r: turn this cell into a markdown cell
x: delete this cell
y: turn this cell back into a ccde cell
z: undo cell deletion

In [3]:
%cd

/Users/hanlei


In [ ]:
%pwd

'/Users/hanlei'

In [ ]:
%cat

In [ ]:
%ls

In [1]:
%run facade.py

booting the FileServer
booting the ProcessServer
trying to create the file 'hello' for user 'foo' with permissions-rw-r-r
trying to create the process 'ls /tmp' for user 'bar'


In [ ]:
%timeit

In [2]:
%pylab inline
# will load numpy as np, matplotlib as

Populating the interactive namespace from numpy and matplotlib


In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [7]:
b[:3]

array([0, 1, 2])

In [8]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [9]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [10]:
np.random.rand(5)

array([ 0.94534139,  0.60950375,  0.63405899,  0.49181451,  0.85809725])

In [11]:
np.fromstring('1 2 3 5 6', sep=' ')


array([ 1.,  2.,  3.,  5.,  6.])

In [14]:
np.loadtxt() # load np array from a file

TypeError: loadtxt() missing 1 required positional argument: 'fname'

In [ ]:
np.loadfile() # load binary

In [16]:
a + 3

array([4, 5, 6, 7])

In [17]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (10,) 